include: package:lints/core.yaml
# include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    # - always_put_required_named_parameters_first
    # - avoid_double_and_int_checks
    # - always_specify_types
    - always_put_control_body_on_new_line

analyzer:
  errors:
    # unused_import: error
    always_declare_return_types: error
